algoritmo "semnome"
// Função :
// Autor :
// Data : 16/04/2019
// Seção de Declarações 
var
resp: caractere
x: inteiro
r: inteiro



inicio
// Seção de Comandos
//A VARIAVEL PRECISA SER INICIADA COM UM VALOR PARA O LOOPING FUNCIONAR
resp <- "sim"

enquanto (resp = "sim") ou (resp = "s") faca
leia(x)
r <- x * 3
escreval(r)

escreval("Deseja continuar")
leia(resp)


fimenquanto











fimalgoritmo
