algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2019
// Seção de Declarações 
var

contador: inteiro
start:  inteiro
numero: inteiro
result: inteiro






inicio
// Seção de Comandos 

start <- 1

escreva("Digite um numero:")
leia(numero)


enquanto (contador <= 10) faca



         escreval(numero, " x", contador, " =", numero * contador)
         contador <- contador + 1
         
fimenquanto









fimalgoritmo
